#!/usr/bin/env bash

TFVARS="./terraform/variables.auto.tfvars"

CLUSTER_NAME=$(awk -F "= " '/cluster_name/ {print $2}' ${TFVARS} | sed 's/"//g')

cd terraform

terraform plan

terraform apply -auto-approve

sleep 5

echo
echo "Now that the GKE cluster has been provisioned we can run a demo/test validation service/pod"
echo

sleep 10 

gcloud container clusters get-credentials $CLUSTER_NAME

echo "run kuard service/pod for demo purposes"
kubectl run --restart=Never --image=gcr.io/kuar-demo/kuard-amd64:blue kuard

echo "sleep for the kuard pods to be ready"
sleep 10

echo "kubectl port-forward 8080:8080"
kubectl port-forward kuard 8080:8080

#open http://localhost:8080/
